-- Ativar extensão de UUID se não estiver ativa
create extension if not exists "uuid-ossp";

-- =========================================================================
-- TABELA DE CLIENTES
-- =========================================================================
create table public.clientes (
    id uuid default gen_random_uuid() primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    user_id uuid references auth.users(id) on delete cascade not null,
    cnpj_cpf text not null,
    nome_fantasia text not null,
    razao_social text,
    cep text,
    rua text,
    numero text,
    bairro text,
    cidade text,
    estado text,
    telefone_1 text not null,
    telefone_2 text,
    email text,
    
    -- Impede CPF/CNPJ duplicado para o mesmo usuário
    constraint unique_user_cnpj_cpf unique (user_id, cnpj_cpf)
);

-- Habilitar RLS (Row Level Security) para segurança
alter table public.clientes enable row level security;

-- Criar políticas de segurança para Clientes
create policy "Usuários autenticados podem cadastrar seus próprios clientes" 
on public.clientes for insert to authenticated 
with check (auth.uid() = user_id);

create policy "Usuários podem ver apenas seus próprios clientes" 
on public.clientes for select to authenticated 
using (auth.uid() = user_id);

create policy "Usuários podem atualizar apenas seus próprios clientes" 
on public.clientes for update to authenticated 
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Usuários podem deletar apenas seus próprios clientes" 
on public.clientes for delete to authenticated 
using (auth.uid() = user_id);


-- =========================================================================
-- TABELA DE PRODUTOS
-- =========================================================================
create table public.produtos (
    id uuid default gen_random_uuid() primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    user_id uuid references auth.users(id) on delete cascade not null,
    codigo bigint generated by default as identity,
    nome_descricao text not null,
    valor numeric(10, 2) not null,
    
    -- Garante código sequencial de produto único (ou sequencial geral)
    constraint unique_product_id unique (id)
);

-- Habilitar RLS para produtos
alter table public.produtos enable row level security;

-- Criar políticas de segurança para Produtos
create policy "Usuários autenticados podem cadastrar seus próprios produtos" 
on public.produtos for insert to authenticated 
with check (auth.uid() = user_id);

create policy "Usuários podem ver apenas seus próprios produtos" 
on public.produtos for select to authenticated 
using (auth.uid() = user_id);

create policy "Usuários podem atualizar apenas seus próprios produtos" 
on public.produtos for update to authenticated 
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Usuários podem deletar apenas seus próprios produtos" 
on public.produtos for delete to authenticated 
using (auth.uid() = user_id);
